"""VideoDead cookiejar — export YouTube cookies from a running Chromium.

Connects to the Chromium container over the DevTools Protocol (CDP), reads all
cookies (plaintext, no decryption needed), writes them as a Netscape cookies.txt
to a shared volume, and repeats on a schedule. The worker uses that file
automatically. One human login in the browser (with 2FA) is required up front.
"""
from __future__ import annotations

import json
import os
import time
import urllib.request

from websocket import create_connection

CDP_HOST = os.getenv("CDP_HOST", "browser:9222")
OUT = os.getenv("COOKIES_OUT", "/cookies/cookies.txt")
INTERVAL = int(os.getenv("EXPORT_INTERVAL", "1800"))


def _browser_ws() -> str:
    info = json.load(urllib.request.urlopen(f"http://{CDP_HOST}/json/version", timeout=10))
    ws = info["webSocketDebuggerUrl"]            # ws://0.0.0.0:9222/devtools/browser/<id>
    path = ws.split("9222", 1)[1]
    return f"ws://{CDP_HOST}{path}"


def _get_cookies() -> list[dict]:
    conn = create_connection(_browser_ws(), timeout=15, header=["Origin: http://localhost"])
    try:
        conn.send(json.dumps({"id": 1, "method": "Storage.getCookies"}))
        while True:
            msg = json.loads(conn.recv())
            if msg.get("id") == 1:
                return msg.get("result", {}).get("cookies", [])
    finally:
        conn.close()


def _to_netscape(cookies: list[dict]) -> str:
    lines = ["# Netscape HTTP Cookie File", "# Auto-generated by VideoDead cookiejar", ""]
    for c in cookies:
        domain = c.get("domain", "")
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expiry = int(c.get("expires") or 0)
        if expiry <= 0:
            expiry = int(time.time()) + 3600 * 24 * 180
        lines.append("\t".join([domain, flag, path, secure, str(expiry),
                                c.get("name", ""), c.get("value", "")]))
    return "\n".join(lines) + "\n"


def run_once() -> None:
    cookies = _get_cookies()
    relevant = [c for c in cookies
                if "youtube" in c.get("domain", "") or "google" in c.get("domain", "")]
    txt = _to_netscape(relevant or cookies)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    tmp = OUT + ".tmp"
    with open(tmp, "w") as f:
        f.write(txt)
    os.replace(tmp, OUT)
    print(f"[cookiejar] wrote {len(relevant or cookies)} cookies -> {OUT}", flush=True)


if __name__ == "__main__":
    while True:
        try:
            run_once()
        except Exception as exc:  # noqa: BLE001
            print(f"[cookiejar] not ready / error: {exc}", flush=True)
        time.sleep(INTERVAL)
